[2023-07-07T16:06:17.078+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_imports_v7.get_data manual__2023-07-07T16:06:16.555566+00:00 [queued]>
[2023-07-07T16:06:17.085+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_imports_v7.get_data manual__2023-07-07T16:06:16.555566+00:00 [queued]>
[2023-07-07T16:06:17.085+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-07T16:06:17.117+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonExternalDecoratedOperator): get_data> on 2023-07-07 16:06:16.555566+00:00
[2023-07-07T16:06:17.123+0000] {standard_task_runner.py:57} INFO - Started process 1155 to run task
[2023-07-07T16:06:17.124+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_imports_v7', 'get_data', 'manual__2023-07-07T16:06:16.555566+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/scrap_data.py', '--cfg-path', '/tmp/tmphs2z7_l4']
[2023-07-07T16:06:17.125+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask get_data
[2023-07-07T16:06:17.158+0000] {task_command.py:410} INFO - Running <TaskInstance: test_imports_v7.get_data manual__2023-07-07T16:06:16.555566+00:00 [running]> on host d409bdcb9602
[2023-07-07T16:06:17.219+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_imports_v7' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-07T16:06:16.555566+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-07T16:06:16.555566+00:00'
[2023-07-07T16:06:17.816+0000] {process_utils.py:181} INFO - Executing cmd: /usr/local/bin/python /tmp/tmdv_tn1juf/script.py /tmp/tmdv_tn1juf/script.in /tmp/tmdv_tn1juf/script.out /tmp/tmdv_tn1juf/string_args.txt
[2023-07-07T16:06:17.826+0000] {process_utils.py:185} INFO - Output:
[2023-07-07T16:06:18.350+0000] {process_utils.py:189} INFO - Traceback (most recent call last):
[2023-07-07T16:06:18.350+0000] {process_utils.py:189} INFO -   File "/tmp/tmdv_tn1juf/script.py", line 29, in <module>
[2023-07-07T16:06:18.351+0000] {process_utils.py:189} INFO -     res = get_data(*arg_dict["args"], **arg_dict["kwargs"])
[2023-07-07T16:06:18.351+0000] {process_utils.py:189} INFO -   File "/tmp/tmdv_tn1juf/script.py", line 26, in get_data
[2023-07-07T16:06:18.351+0000] {process_utils.py:189} INFO -     from selenium import webdriver
[2023-07-07T16:06:18.351+0000] {process_utils.py:189} INFO - ModuleNotFoundError: No module named 'selenium'
[2023-07-07T16:06:18.387+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 374, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 696, in execute_callable
    return self._execute_python_callable_in_subprocess(python_path, tmp_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 434, in _execute_python_callable_in_subprocess
    os.fspath(string_args_path),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 170, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 193, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '/tmp/tmdv_tn1juf/script.py', '/tmp/tmdv_tn1juf/script.in', '/tmp/tmdv_tn1juf/script.out', '/tmp/tmdv_tn1juf/string_args.txt']' returned non-zero exit status 1.
[2023-07-07T16:06:18.396+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=test_imports_v7, task_id=get_data, execution_date=20230707T160616, start_date=20230707T160617, end_date=20230707T160618
[2023-07-07T16:06:18.408+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 71 for task get_data (Command '['/usr/local/bin/python', '/tmp/tmdv_tn1juf/script.py', '/tmp/tmdv_tn1juf/script.in', '/tmp/tmdv_tn1juf/script.out', '/tmp/tmdv_tn1juf/string_args.txt']' returned non-zero exit status 1.; 1155)
[2023-07-07T16:06:18.423+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-07T16:06:18.443+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
