[2023-07-07T16:06:14.902+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_imports_v7.get_data scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-07T16:06:14.907+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_imports_v7.get_data scheduled__2023-07-05T00:00:00+00:00 [queued]>
[2023-07-07T16:06:14.908+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-07T16:06:14.917+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonExternalDecoratedOperator): get_data> on 2023-07-05 00:00:00+00:00
[2023-07-07T16:06:14.922+0000] {standard_task_runner.py:57} INFO - Started process 1146 to run task
[2023-07-07T16:06:14.924+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_imports_v7', 'get_data', 'scheduled__2023-07-05T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/scrap_data.py', '--cfg-path', '/tmp/tmp7drs0jvv']
[2023-07-07T16:06:14.925+0000] {standard_task_runner.py:85} INFO - Job 70: Subtask get_data
[2023-07-07T16:06:14.955+0000] {task_command.py:410} INFO - Running <TaskInstance: test_imports_v7.get_data scheduled__2023-07-05T00:00:00+00:00 [running]> on host d409bdcb9602
[2023-07-07T16:06:15.013+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_imports_v7' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-05T00:00:00+00:00'
[2023-07-07T16:06:15.609+0000] {process_utils.py:181} INFO - Executing cmd: /usr/local/bin/python /tmp/tmdstjgkno8/script.py /tmp/tmdstjgkno8/script.in /tmp/tmdstjgkno8/script.out /tmp/tmdstjgkno8/string_args.txt
[2023-07-07T16:06:15.619+0000] {process_utils.py:185} INFO - Output:
[2023-07-07T16:06:16.142+0000] {process_utils.py:189} INFO - Traceback (most recent call last):
[2023-07-07T16:06:16.142+0000] {process_utils.py:189} INFO -   File "/tmp/tmdstjgkno8/script.py", line 29, in <module>
[2023-07-07T16:06:16.142+0000] {process_utils.py:189} INFO -     res = get_data(*arg_dict["args"], **arg_dict["kwargs"])
[2023-07-07T16:06:16.142+0000] {process_utils.py:189} INFO -   File "/tmp/tmdstjgkno8/script.py", line 26, in get_data
[2023-07-07T16:06:16.142+0000] {process_utils.py:189} INFO -     from selenium import webdriver
[2023-07-07T16:06:16.143+0000] {process_utils.py:189} INFO - ModuleNotFoundError: No module named 'selenium'
[2023-07-07T16:06:16.182+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 374, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 696, in execute_callable
    return self._execute_python_callable_in_subprocess(python_path, tmp_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 434, in _execute_python_callable_in_subprocess
    os.fspath(string_args_path),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 170, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 193, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '/tmp/tmdstjgkno8/script.py', '/tmp/tmdstjgkno8/script.in', '/tmp/tmdstjgkno8/script.out', '/tmp/tmdstjgkno8/string_args.txt']' returned non-zero exit status 1.
[2023-07-07T16:06:16.189+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=test_imports_v7, task_id=get_data, execution_date=20230705T000000, start_date=20230707T160614, end_date=20230707T160616
[2023-07-07T16:06:16.199+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 70 for task get_data (Command '['/usr/local/bin/python', '/tmp/tmdstjgkno8/script.py', '/tmp/tmdstjgkno8/script.in', '/tmp/tmdstjgkno8/script.out', '/tmp/tmdstjgkno8/string_args.txt']' returned non-zero exit status 1.; 1146)
[2023-07-07T16:06:16.222+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-07T16:06:16.234+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
